## Matrix manipulation

#### 1.Using numpy

In [1]:
import numpy as np

In [2]:
a = np.array([[0.4, 0.2, 0.4]])
w = np.array([[-0.5, -0.2],
               [-0.3, 0.4],
               [-0.5, 0.2]])
b = np.array([[0.1, 0.2]])

In [3]:
xwb = a.dot(w) + b
print(xwb)
def relu(a):
    a[a<0] = 0
    return a

[[-0.36  0.28]]


In [4]:
relu(xwb)

array([[0.  , 0.28]])

#### 2. Using tensorflow

In [5]:
import tensorflow as tf

In [6]:
x = tf.Variable([[0.4, 0.2, 0.4]])
w = tf.Variable([[-0.5, -0.2],
               [-0.3, 0.4],
               [-0.5, 0.2]])
b = tf.Variable([[0.1, 0.2]])
y = tf.matmul(x, w) + b
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("xwb:");print(sess.run(y))
    print("relu:");print(sess.run(tf.nn.relu(y)))

xwb:
[[-0.36000004  0.28      ]]
relu:
[[0.   0.28]]


#### 3.Initializing the valuew with standard normal distribution

##### 3-1: Using numpy library

In [10]:
x = np.array([[0.4, 0.2, 0.4]])
w = np.random.randn(3, 2)
b = np.random.randn(1, 2)
print(w);print(b)
xwb = x.dot(w) + b
print(xwb)
y = relu(xwb)
print(y)

[[ 0.9724167   0.01261378]
 [-0.99284822  0.39216896]
 [ 0.0749017   0.37621181]]
[[-2.16862612  0.61789298]]
[[-1.9482684   0.85185701]]
[[0.         0.85185701]]


##### 3-2: Using tensorflow library

In [13]:
t_x = tf.Variable([[0.4, 0.2, 0.4]])
t_w = tf.random_normal(shape=(3, 2))
t_b = tf.random_normal(shape=(1, 2))
t_xwb = tf.matmul(t_x, t_w) + t_b
t_y = tf.nn.relu(t_xwb)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    (b, w, y) = sess.run([t_b, t_w, t_y])
    print(b);print(w);print(y)   

[[0.5732507  0.87966853]]
[[-2.1641607  -0.6248603 ]
 [-1.0683779  -1.8003294 ]
 [ 1.0584977  -0.16282682]]
[[0.        0.2045278]]
