## Matrix manipulation

#### 1.Using numpy

In [2]:
import numpy as np

In [3]:
a = np.array([[0.4, 0.2, 0.4]])
w = np.array([[-0.5, -0.2],
               [-0.3, 0.4],
               [-0.5, 0.2]])
b = np.array([[0.1, 0.2]])

In [4]:
xwb = a.dot(w) + b
print(xwb)
def relu(a):
    a[a<0] = 0
    return a

[[-0.36  0.28]]


In [5]:
relu(xwb)

array([[0.  , 0.28]])

#### 2. Using tensorflow

In [6]:
import tensorflow as tf

In [7]:
x = tf.Variable([[0.4, 0.2, 0.4]])
w = tf.Variable([[-0.5, -0.2],
               [-0.3, 0.4],
               [-0.5, 0.2]])
b = tf.Variable([[0.1, 0.2]])
y = tf.matmul(x, w) + b
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("xwb:");print(sess.run(y))
    print("relu:");print(sess.run(tf.nn.relu(y)))

xwb:


[[-0.36000004  0.28      ]]
relu:
[[0.   0.28]]
